server:
  port: 8080

spring:
  application:
    name: shopping-category
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:h2:mem:musinsa;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_UPPER=false
#    url: jdbc:h2:mem:musinsa;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_UPPER=true # 대문자로 통일
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true # 큰따옴표 제거
        globally_quoted_identifiers_skip_column_definitions: true
        auto_quoting_enabled: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 50
        dialect: org.hibernate.dialect.H2Dialect

springdoc:
  show-actuator: false
  swagger-ui:
    enabled: true
    tagsSorter: alpha

logging:
  level:
    org.hibernate.tool.schema: ERROR